services:
  mariadb:
    image: mariadb:${MARIADB_TAG:-10.11.8}
    hostname: mariadb
    container_name: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: ${IMAGE:-slurm-docker-cluster-gpu}:${IMAGE_TAG:-23.02.7}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mariadb

  slurmctld:
    image: ${IMAGE:-slurm-docker-cluster-gpu}:${IMAGE_TAG:-23.02.7}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ${ROOT_HOME:-./.root_home}:/root
    env_file:
      - .env
    shm_size: 8gb
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_NICE
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  c1:
    image: ${IMAGE:-slurm-docker-cluster-gpu}:${IMAGE_TAG:-23.02.7}
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ${ROOT_HOME:-./.root_home}:/root
    env_file:
      - .env
    shm_size: 8gb
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_NICE
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: ${IMAGE:-slurm-docker-cluster-gpu}:${IMAGE_TAG:-23.02.7}
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ${ROOT_HOME:-./.root_home}:/root
    env_file:
      - .env
    shm_size: 8gb
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_NICE
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  etc_slurm:
  var_lib_mysql:
  var_log_slurm:
